# -*- coding: utf-8 -*-
"""242. Valid Anagram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GkMNHaGCKpBvM3OiZ8MN45V6si8kyQ4r
"""

from collections import Counter

class Solution:
    def isAnagram(self, s: str, t: str) -> bool:
        if Counter(s) == Counter(t):
            return True
        else:
            return False

s = "anagram"
t = "nagaram"

s = "rat"
t = "car"