# -*- coding: utf-8 -*-
"""387. First Unique Character in a String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PgpiKZdjd_AJ3oRgep76idJYueKqJEi_
"""

from collections import Counter

class Solution:
    def firstUniqChar(self, s: str) -> int:
        s_count = Counter(list(s))
        target = [list(s_count.keys())[i] for i in range(len(s_count)) if list(s_count.values())[i]==1]
        result = [s.index(i) for i in target]
        if len(result) > 0:
          return min(result)
        else:
          return -1

s = "leetcode"
s = "loveleetcode"