# -*- coding: utf-8 -*-
"""Merged_Sorted_Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Wz1KmC60jj4ZvSpdvoXNTgAUvaBYT_1
"""

nums1 = [1,2,3,0,0,0]
nums2 = [2,5,6]
m = 3
n = 3

class Solution:
    def merge(self, nums1: List[int], m: int, nums2: List[int], n: int) -> None:
        """
        Do not return anything, modify nums1 in-place instead.
        """
        nums1[:(m+n)] = sorted(nums1[:m] + nums2[:n])